import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import bcrypt from 'bcryptjs';
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import { db } from './db.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const UPLOADS_DIR = path.join(__dirname, 'uploads');
if (!fs.existsSync(UPLOADS_DIR)) {
  fs.mkdirSync(UPLOADS_DIR, { recursive: true });
}

async function generateMockPDF(filename, text) {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([500, 700]);
  const font = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const regularFont = await pdfDoc.embedFont(StandardFonts.Helvetica);

  // Draw Header
  page.drawText(text, {
    x: 50,
    y: 600,
    size: 24,
    font,
    color: rgb(0.5, 0.3, 0.9), // Purple branding
  });

  // Draw Description Paragraph
  page.drawText('This is a simulated service agreement generated by Signy.', {
    x: 50,
    y: 540,
    size: 11,
    font: regularFont,
    color: rgb(0.2, 0.2, 0.2),
  });

  page.drawText('By signing below, both parties agree to the terms of this document.', {
    x: 50,
    y: 520,
    size: 11,
    font: regularFont,
    color: rgb(0.2, 0.2, 0.2),
  });

  // Draw line for decoration
  page.drawLine({
    start: { x: 50, y: 480 },
    end: { x: 450, y: 480 },
    thickness: 1,
    color: rgb(0.8, 0.8, 0.8),
  });

  const pdfBytes = await pdfDoc.save();
  const filePath = path.join(UPLOADS_DIR, filename);
  fs.writeFileSync(filePath, pdfBytes);
  console.log(`Generated mock PDF at: ${filePath}`);
}

async function runSeed() {
  console.log('Seeding local mock database...');

  try {
    // Generate Mock PDF
    await generateMockPDF('mock_service_agreement.pdf', 'Service Agreement');

    // Create User "Alice"
    const salt = await bcrypt.genSalt(10);
    const passwordHash = await bcrypt.hash('password123', salt);

    const user = await db.users.create({
      name: 'Alice Cooper',
      email: 'alice@example.com',
      passwordHash
    });

    console.log(`Created user: ${user.email} (Password: password123)`);

    // Create Document record
    const doc = await db.documents.create({
      name: 'mock_service_agreement.pdf',
      filePath: '/uploads/mock_service_agreement.pdf',
      ownerId: user.id,
      status: 'Pending'
    });

    console.log(`Created document record for ID: ${doc.id}`);

    // Create signature placeholder for Bob
    const sig = await db.signatures.create({
      documentId: doc.id,
      x: 20,
      y: 65,
      page: 1,
      signerEmail: 'bob@example.com'
    });

    console.log(`Created signature placeholder for ${sig.signer_email} at coordinates x:${sig.x}, y:${sig.y}`);

    // Create Audit Log
    await db.auditLogs.create({
      documentId: doc.id,
      action: 'Uploaded Document (Seeded)',
      userEmail: 'alice@example.com'
    });

    console.log('Database successfully seeded!');
  } catch (error) {
    console.error('Seeding failed:', error);
  }
}

runSeed();
